//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RC.ProtoGen.Properties {
	/// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProtocolGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 namespace Protocol.Gen
        ///{
        ///	public static class Module
        ///	{
        ///		[modules]
        ///	}
        ///
        ///	public static class Command
        ///	{
        ///		[packets]
        ///	}
        ///} 的本地化字符串。
        /// </summary>
        internal static string const_template {
            get {
                return ResourceManager.GetString("const_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///	&quot;write&quot;:{
        ///		&quot;byte&quot;:&quot;Write&quot;,
        ///		&quot;bool&quot;:&quot;Write&quot;,
        ///		&quot;int&quot;:&quot;Write&quot;,
        ///		&quot;uint&quot;:&quot;Write&quot;,
        ///		&quot;float&quot;:&quot;Write&quot;,
        ///		&quot;short&quot;:&quot;Write&quot;,
        ///		&quot;ushort&quot;:&quot;Write&quot;,
        ///		&quot;long&quot;:&quot;Write&quot;,
        ///		&quot;ulong&quot;:&quot;Write&quot;,
        ///		&quot;double&quot;:&quot;Write&quot;,
        ///		&quot;string&quot;:&quot;WriteUTF8&quot;,
        ///		&quot;string2&quot;:&quot;WriteUTF8E&quot;
        ///	},
        ///	&quot;read&quot;:{
        ///		&quot;byte&quot;:&quot;ReadByte&quot;,
        ///		&quot;bool&quot;:&quot;ReadBool&quot;,
        ///		&quot;int&quot;:&quot;ReadInt&quot;,
        ///		&quot;uint&quot;:&quot;ReadUInt&quot;,
        ///		&quot;float&quot;:&quot;ReadFloat&quot;,
        ///		&quot;short&quot;:&quot;ReadShort&quot;,
        ///		&quot;ushort&quot;:&quot;ReadUShort&quot;,
        ///		&quot;long&quot;:&quot;ReadLong&quot;,
        ///		&quot;ulong&quot;:&quot;ReadULong&quot;,
        ///		&quot;double&quot;:&quot;ReadDouble&quot;,
        ///		 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string convertions {
            get {
                return ResourceManager.GetString("convertions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System.Collections.Generic;
        ///using RC.Core.Net;
        ///using RC.Core.Net.Protocol;
        ///
        ///namespace Protocol.Gen
        ///{
        ///	public class [cls_name] : DTO
        ///	{
        ///		[fields \n]public [field_type] [field_name];[/fields]
        ///		
        ///		[ctors \n]public [cls_name]( [fields ,][field_type] [field_name][/fields] )
        ///		{
        ///			[fields \n]this.[field_name] = [field_name];[/fields]
        ///		}[/ctors]
        ///
        ///		protected override void InternalSerialize( StreamBuffer buffer )
        ///		{
        ///			base.InternalSerialize( buffer );
        ///
        ///			[condition \n]if ( [key] == [value] [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string dto_template {
            get {
                return ResourceManager.GetString("dto_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // ReSharper disable UnusedMember.Global
        ///// ReSharper disable InconsistentNaming
        ///using RC.Core.Net;
        ///using RC.Core.Net.Protocol;
        ///using System;
        ///using System.Collections.Generic;
        ///
        ///namespace Protocol.Gen
        ///{
        ///	public static class ProtocolManager
        ///	{
        ///		private static readonly Dictionary&lt;ushort, Type&gt; DTO_MAP = new Dictionary&lt;ushort, Type&gt;
        ///		{
        ///			[dtos \n]{ [id], typeof( [dto_cls_name] ) },[/dtos]
        ///		};
        ///
        ///		private static readonly Dictionary&lt;int, Type&gt; PACKET_MAP = new Dictionary&lt;int, Type&gt;
        ///		{
        ///			[packets  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string mgr_template {
            get {
                return ResourceManager.GetString("mgr_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using RC.Core.Net;
        ///using RC.Core.Net.Protocol;
        ///
        ///namespace Protocol.Gen
        ///{
        ///	public class [cls_name] : Packet
        ///	{
        ///		[option]public [dto_cls_name] dto;[/option]
        ///
        ///		public [cls_name]() : base( [module], [cmd] )
        ///		{
        ///		}
        ///
        ///		[option]public [cls_name]( [dto_cls_name] dto ) : base( [module], [cmd] )
        ///		{
        ///			this.dto = dto;
        ///		}
        ///
        ///		[ctors \n]public [cls_name]( [fields ,][field_type] [field_name][/fields] ) : base( [module], [cmd] )
        ///		{
        ///			this.dto = new [dto_cls_name]( [fields ,][field_name][/fields] );
        ///		 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string packet_template {
            get {
                return ResourceManager.GetString("packet_template", resourceCulture);
            }
        }
    }
}
